/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Point {
    lat: number;
    lon: number;
}
export interface Session {
    id: bigint;
    startTime: bigint;
    duration: bigint;
    skipperName: string;
    userId: string;
    distance: number;
    pointsCount: bigint;
    finalTime?: bigint;
    routeId: bigint;
    boatName: string;
    rating: bigint;
    positions: Array<Position>;
    intermediateTime?: bigint;
}
export interface Position {
    lat: number;
    lon: number;
    timestamp: bigint;
}
export interface UserProfile {
    boatCategory: string;
    username: string;
    email: string;
    boatRating: bigint;
    boatName: string;
}
export interface Route {
    id: bigint;
    userId: string;
    name: string;
    startPoint1: Point;
    startPoint2: Point;
    intermediatePoint1: Point;
    intermediatePoint2: Point;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createRoute(name: string, startPoint1: Point, startPoint2: Point, intermediatePoint1: Point, intermediatePoint2: Point, userId: string): Promise<bigint>;
    deleteRoute(routeId: bigint, userId: string): Promise<boolean>;
    findRoutesWithinDistance(lat: number, lon: number, maxDistance: number, userId: string): Promise<Array<Route>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentTime(): Promise<bigint>;
    getLastSessionForUser(userId: string): Promise<Session | null>;
    getRoute(routeId: bigint): Promise<Route | null>;
    getRoutes(userId: string): Promise<Array<Route>>;
    getSession(id: bigint): Promise<Session | null>;
    getSessionCount(): Promise<bigint>;
    getSessions(): Promise<Array<Session>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSessions(userId: string): Promise<Array<Session>>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveSession(startTime: bigint, duration: bigint, positions: Array<Position>, distance: number, skipperName: string, boatName: string, rating: bigint, userId: string, routeId: bigint, intermediateTime: bigint | null, finalTime: bigint | null): Promise<bigint>;
    updateRoute(routeId: bigint, name: string, startPoint1: Point, startPoint2: Point, intermediatePoint1: Point, intermediatePoint2: Point, userId: string): Promise<boolean>;
}
import type { Position as _Position, Route as _Route, Session as _Session, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createRoute(arg0: string, arg1: Point, arg2: Point, arg3: Point, arg4: Point, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoute(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoute(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteRoute(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRoute(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRoute(arg0, arg1);
            return result;
        }
    }
    async findRoutesWithinDistance(arg0: number, arg1: number, arg2: number, arg3: string): Promise<Array<Route>> {
        if (this.processError) {
            try {
                const result = await this.actor.findRoutesWithinDistance(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findRoutesWithinDistance(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCurrentTime(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTime();
            return result;
        }
    }
    async getLastSessionForUser(arg0: string): Promise<Session | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastSessionForUser(arg0);
                return from_candid_opt_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastSessionForUser(arg0);
            return from_candid_opt_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRoute(arg0: bigint): Promise<Route | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoute(arg0);
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoute(arg0);
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRoutes(arg0: string): Promise<Array<Route>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutes(arg0);
            return result;
        }
    }
    async getSession(arg0: bigint): Promise<Session | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSessionCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionCount();
            return result;
        }
    }
    async getSessions(): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessions();
                return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessions();
            return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserSessions(arg0: string): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSessions(arg0);
                return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSessions(arg0);
            return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveSession(arg0: bigint, arg1: bigint, arg2: Array<Position>, arg3: number, arg4: string, arg5: string, arg6: bigint, arg7: string, arg8: bigint, arg9: bigint | null, arg10: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSession(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n12(this.uploadFile, this.downloadFile, arg9), to_candid_opt_n12(this.uploadFile, this.downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSession(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n12(this.uploadFile, this.downloadFile, arg9), to_candid_opt_n12(this.uploadFile, this.downloadFile, arg10));
            return result;
        }
    }
    async updateRoute(arg0: bigint, arg1: string, arg2: Point, arg3: Point, arg4: Point, arg5: Point, arg6: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoute(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoute(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
}
function from_candid_Session_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n8(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Route]): Route | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Session]): Session | null {
    return value.length === 0 ? null : from_candid_Session_n7(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: bigint;
    duration: bigint;
    skipperName: string;
    userId: string;
    distance: number;
    pointsCount: bigint;
    finalTime: [] | [bigint];
    routeId: bigint;
    boatName: string;
    rating: bigint;
    positions: Array<_Position>;
    intermediateTime: [] | [bigint];
}): {
    id: bigint;
    startTime: bigint;
    duration: bigint;
    skipperName: string;
    userId: string;
    distance: number;
    pointsCount: bigint;
    finalTime?: bigint;
    routeId: bigint;
    boatName: string;
    rating: bigint;
    positions: Array<Position>;
    intermediateTime?: bigint;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        duration: value.duration,
        skipperName: value.skipperName,
        userId: value.userId,
        distance: value.distance,
        pointsCount: value.pointsCount,
        finalTime: record_opt_to_undefined(from_candid_opt_n9(uploadFile, downloadFile, value.finalTime)),
        routeId: value.routeId,
        boatName: value.boatName,
        rating: value.rating,
        positions: value.positions,
        intermediateTime: record_opt_to_undefined(from_candid_opt_n9(uploadFile, downloadFile, value.intermediateTime))
    };
}
function from_candid_variant_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Session>): Array<Session> {
    return value.map((x)=>from_candid_Session_n7(uploadFile, downloadFile, x));
}
function to_candid_UserRole_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_opt_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}