/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Point = IDL.Record({ 'lat' : IDL.Float64, 'lon' : IDL.Float64 });
export const Route = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'startPoint1' : Point,
  'startPoint2' : Point,
  'intermediatePoint1' : Point,
  'intermediatePoint2' : Point,
});
export const UserProfile = IDL.Record({
  'boatCategory' : IDL.Text,
  'username' : IDL.Text,
  'email' : IDL.Text,
  'boatRating' : IDL.Nat,
  'boatName' : IDL.Text,
});
export const Position = IDL.Record({
  'lat' : IDL.Float64,
  'lon' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'duration' : IDL.Int,
  'skipperName' : IDL.Text,
  'userId' : IDL.Text,
  'distance' : IDL.Float64,
  'pointsCount' : IDL.Nat,
  'finalTime' : IDL.Opt(IDL.Int),
  'routeId' : IDL.Nat,
  'boatName' : IDL.Text,
  'rating' : IDL.Nat,
  'positions' : IDL.Vec(Position),
  'intermediateTime' : IDL.Opt(IDL.Int),
});

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoute' : IDL.Func(
      [IDL.Text, Point, Point, Point, Point, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteRoute' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'findRoutesWithinDistance' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Vec(Route)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentTime' : IDL.Func([], [IDL.Int], ['query']),
  'getLastSessionForUser' : IDL.Func([IDL.Text], [IDL.Opt(Session)], ['query']),
  'getRoute' : IDL.Func([IDL.Nat], [IDL.Opt(Route)], ['query']),
  'getRoutes' : IDL.Func([IDL.Text], [IDL.Vec(Route)], ['query']),
  'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(Session)], ['query']),
  'getSessionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSessions' : IDL.Func([IDL.Text], [IDL.Vec(Session)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSession' : IDL.Func(
      [
        IDL.Int,
        IDL.Int,
        IDL.Vec(Position),
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
      ],
      [IDL.Nat],
      [],
    ),
  'updateRoute' : IDL.Func(
      [IDL.Nat, IDL.Text, Point, Point, Point, Point, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Point = IDL.Record({ 'lat' : IDL.Float64, 'lon' : IDL.Float64 });
  const Route = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'startPoint1' : Point,
    'startPoint2' : Point,
    'intermediatePoint1' : Point,
    'intermediatePoint2' : Point,
  });
  const UserProfile = IDL.Record({
    'boatCategory' : IDL.Text,
    'username' : IDL.Text,
    'email' : IDL.Text,
    'boatRating' : IDL.Nat,
    'boatName' : IDL.Text,
  });
  const Position = IDL.Record({
    'lat' : IDL.Float64,
    'lon' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'duration' : IDL.Int,
    'skipperName' : IDL.Text,
    'userId' : IDL.Text,
    'distance' : IDL.Float64,
    'pointsCount' : IDL.Nat,
    'finalTime' : IDL.Opt(IDL.Int),
    'routeId' : IDL.Nat,
    'boatName' : IDL.Text,
    'rating' : IDL.Nat,
    'positions' : IDL.Vec(Position),
    'intermediateTime' : IDL.Opt(IDL.Int),
  });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoute' : IDL.Func(
        [IDL.Text, Point, Point, Point, Point, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteRoute' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'findRoutesWithinDistance' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Vec(Route)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentTime' : IDL.Func([], [IDL.Int], ['query']),
    'getLastSessionForUser' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Session)],
        ['query'],
      ),
    'getRoute' : IDL.Func([IDL.Nat], [IDL.Opt(Route)], ['query']),
    'getRoutes' : IDL.Func([IDL.Text], [IDL.Vec(Route)], ['query']),
    'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(Session)], ['query']),
    'getSessionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSessions' : IDL.Func([IDL.Text], [IDL.Vec(Session)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSession' : IDL.Func(
        [
          IDL.Int,
          IDL.Int,
          IDL.Vec(Position),
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
        ],
        [IDL.Nat],
        [],
      ),
    'updateRoute' : IDL.Func(
        [IDL.Nat, IDL.Text, Point, Point, Point, Point, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };